Projekt/website/views.py
from flask import Blueprint, render_template, request, flash, jsonify, redirect, url_for
from flask_login import login_required, current_user
from .models import Note
from .models import Transaction
from .models import Category
from . import db
import json
from sqlalchemy.sql import func
import locale

views = Blueprint('views', __name__)



locale.setlocale(locale.LC_ALL, 'sk_SR') 


@views.route('/', methods=['GET', 'POST'])
@login_required
def home():
    name = current_user.first_name

    income =  db.session.query(db.func.sum(Transaction.amount)).filter(Transaction.type == "príjem", Transaction.user_id==current_user.id).first()

    print(income[0])
   
    if income[0] is None:
        income = 0.00
    else:
        income = income[0]

    totalIncome = (locale.format_string('%.2f', income, True))
    
    
    expense = db.session.query(db.func.sum(Transaction.amount)).filter(Transaction.type == "výdaj", Transaction.user_id==current_user.id).first() 
    print(expense[0])
    
    if expense[0] is None:
        expense = 0.00
    else:
        expense = expense[0]

    totalExpense = (locale.format_string('%.2f', expense, True))
    
    balance = income-expense
   
   
    formattedBalance = (locale.format_string('%.2f', balance, True))


    #tu menime 
    income_vs_expense = db.session.query(db.func.sum(Transaction.amount), Transaction.type).group_by(Transaction.type).order_by(Transaction.type).filter(Transaction.user_id == current_user.id).all()

    category_comparison = db.session.query(db.func.sum(Transaction.amount), Transaction.category).group_by(Transaction.category).order_by(Transaction.category).filter(Transaction.user_id == current_user.id, Transaction.type == 'príjem').all()

    vydaje_udaje = db.session.query(db.func.sum(Transaction.amount), Transaction.category).group_by(Transaction.category).order_by(Transaction.category).filter(Transaction.user_id == current_user.id, Transaction.type == 'výdaj').all()

    dates = db.session.query(db.func.sum(Transaction.amount), Transaction.date).group_by(Transaction.date).order_by(Transaction.date).filter(Transaction.user_id == current_user.id).all()

    

    income_category = []
    cats_labels = []
    for amounts, category in  category_comparison:
        income_category.append(amounts)
        cats_labels.append(category)


    expense_category = []
    expense_cats_labels = []
    for amounts, category in  vydaje_udaje:
        expense_category.append(amounts)
        expense_cats_labels.append(category)


    
    income_expense = []
    prijem_vydaj_labels = []
    for total_amount, label in income_vs_expense:
        income_expense.append(total_amount)
        prijem_vydaj_labels.append(label)

    over_time_expenditure = []
    dates_label = []
    for amount, date in dates:
        dates_label.append(date.strftime("%m-%d-%y"))
        over_time_expenditure.append(amount)

                        
    
    return render_template("home.html", text=name, user=current_user, totalIncome=totalIncome, totalExpense=totalExpense, balance=formattedBalance,
    income_vs_expense=json.dumps(income_expense),
                            prijem_vydaj_labels=json.dumps( prijem_vydaj_labels),
                            income_category=json.dumps(income_category),
                            cats_labels = json.dumps(cats_labels),
                            over_time_expenditure=json.dumps(over_time_expenditure),
                            dates_label =json.dumps(dates_label),

                            
                            expense_category = json.dumps(expense_category),

                            expense_cats_labels = json.dumps(expense_cats_labels)

    
    )






@views.route('/delete-note', methods=['POST'])
def delete_note():
    note = json.loads(request.data)
    noteId = note['noteId']
    note = Note.query.get(noteId)
    if note:
        if note.user_id == current_user.id:
            db.session.delete(note)
            db.session.commit()
            
            

    return jsonify({})





@views.route('/wishlist', methods=['GET', 'POST'])
@login_required
def wishlist():  
    if request.method == 'POST':
        note = request.form.get('note')

        if len(note) < 1:
            flash('Názov je príliš krátky!', category='error')
        else:
            new_note = Note(data=note, user_id=current_user.id)
            db.session.add(new_note)
            db.session.commit()
           
        
        
            

    return render_template("wishlist.html", user=current_user)





@views.route('/transactions', methods=['GET', 'POST'])
@login_required
def transactions(): 
    entries = Transaction.query.order_by(Transaction.date.desc()).filter(Transaction.user_id == current_user.id).all()
    return render_template("transactions.html", user=current_user, entries=entries)



@views.route('/categories', methods=['GET', 'POST'])
@login_required
def categories(): 
    entries = Category.query.order_by(Category.id.desc()).filter(Category.user_id == current_user.id).all()
    return render_template("categories.html", user=current_user, entries=entries)






@views.route("/addCategory", methods=["GET", "POST"])
def addCategory():
   
    if request.method == 'POST':
        name = request.form['name']
       

        str = request.form['icon']
        arr = str.split("|")
        icon = arr[0]
        type = arr[1]
        user_id = current_user.id

      
    
        entry = Category(type, name, icon, user_id)
        db.session.add(entry)
        db.session.commit()
      
        flash("Kategória bola pridaná",'success')
        return redirect(url_for('views.categories'))
    return render_template('addCategory.html',user=current_user)





@views.route('/deleteCategory/<int:id>')
def deleteCategory(id):
    row = Category.query.get_or_404(int(id))
    db.session.delete(row)
    db.session.commit()
 
   
    flash('Kategória bola vymazaná.', 'success close')
    return redirect(url_for('views.categories'))





@views.route("/addTransaction", methods=["GET", "POST"])
def addTransaction():
    
    categories = Category.query.order_by(Category.id.desc()).filter(Category.user_id == current_user.id).all()
    
    if request.method == 'POST':   
        
        str = request.form['icon']
        arr = str.split("|")
        category = arr[0]
        type = arr[1]
        user_id = current_user.id

      
        amount = request.form['amount']
        
       
        
        entry = Transaction(type, category, amount, user_id)
        db.session.add(entry)
        db.session.commit()
     
        flash("Transakcia bola pridaná",'success')
        return redirect(url_for('views.transactions'))
    return render_template('addTransaction.html',user=current_user, categories=categories)
    







@views.route("/editTransaction/<int:id>", methods=["GET", "POST"])
def editTransaction(id):  
    transaction = Transaction.query.get_or_404(id)
    categories = Category.query.order_by(Category.id.desc()).filter(Category.user_id == current_user.id).all()
    if request.method == 'POST':
        transaction.amount = request.form['amount']
        str= request.form['icon']
        arr = str.split("|")
        transaction.category=arr[0]
        transaction.type=arr[1]
        try:
            db.session.commit() 
            flash("Transakcia bola upravená",'success')
            return redirect('/transactions')
        except:
            return "Nepodarilo sa editovať transakciu"
    else:
        return render_template('editTransaction.html', transaction = transaction, categories=categories)
                    
                    

   




@views.route('/delete/<int:id>')
def delete(id):
    row = Transaction.query.get_or_404(int(id))
    db.session.delete(row)
    db.session.commit()
 
   
    flash('Položka bola vymazaná.', 'success close')
    return redirect(url_for('views.transactions'))




@views.route("/charts", methods=["GET", "POST"])
def charts():
  
    income_vs_expense = db.session.query(db.func.sum(Transaction.amount), Transaction.type).group_by(Transaction.type).order_by(Transaction.type).filter(Transaction.user_id == current_user.id).all()

    category_comparison = db.session.query(db.func.sum(Transaction.amount), Transaction.category).group_by(Transaction.category).order_by(Transaction.category).filter(Transaction.user_id == current_user.id, Transaction.type == 'príjem').all()

    vydaje_udaje = db.session.query(db.func.sum(Transaction.amount), Transaction.category).group_by(Transaction.category).order_by(Transaction.category).filter(Transaction.user_id == current_user.id, Transaction.type == 'výdaj').all()

    dates = db.session.query(db.func.sum(Transaction.amount), Transaction.date).group_by(Transaction.date).order_by(Transaction.date).filter(Transaction.user_id == current_user.id).all()

    entries = Transaction.query.order_by(Transaction.date.desc()).filter(Transaction.user_id == current_user.id).all()
    


    income_category = []
    cats_labels = []
    for amounts, category in  category_comparison:
        income_category.append(amounts)
        cats_labels.append(category)


    expense_category = []
    expense_cats_labels = []
    for amounts, category in  vydaje_udaje:
        expense_category.append(amounts)
        expense_cats_labels.append(category)


    
    income_expense = []
    prijem_vydaj_labels = []
    for total_amount, label in income_vs_expense:
        income_expense.append(total_amount)
        prijem_vydaj_labels.append(label)

    over_time_expenditure = []
    dates_label = []
    for amount, date in dates:
        dates_label.append(date.strftime("%m-%d-%y"))
        over_time_expenditure.append(amount)
        
    return render_template('charts.html',user=current_user, entries=entries,
    income_vs_expense=json.dumps(income_expense),
                            prijem_vydaj_labels=json.dumps( prijem_vydaj_labels),

Projekt/website/templates/addCategory.html
{% extends 'base.html' %}
{% block content %}
<div class="col-xs-10 col-sm-6 col-md-6 ml-auto mr-auto">
    <div class="card card-style mb-2">
        <div class="card-body">
            <form action="{{url_for('views.addCategory')}}" method="POST">
                <fieldset class="form-group">
                    <legend class="mb-4">Nová Kategória</legend>
                  
                  <br>
            
            
                    <div class="form-group">
                       
                        <label class="inputLabel" for="name" >Názov</label>
                        
                        <input type="text" required id="name" name="name" autocomplete="off">


                    </div>

                  
                    
                    
            

 



                        
           
<div class="categories-box">


                                            <input type="radio" name="icon" id="home" value="fa-solid fa-house|výdaj">
                                            <label  for="home"><i class="fa-solid fa-house icons"></i></label>
                                        


                                            <input type="radio" name="icon" id="groceries" value="fa-solid fa-cart-shopping|výdaj">
                                            <label  for="groceries"><i class="fa-solid fa-cart-shopping icons"></i></label>

                                                <input type="radio" name="icon" id="clothes" value="fa-solid fa-shirt|výdaj">
                                                <label  for="clothes"><i class="fa-solid fa-shirt icons"></i></label>
                                           

                                           
                                                    <input type="radio" name="icon" id="cosmetics" value="fa-solid fa-spray-can-sparkles|výdaj">
                                                    <label  for="cosmetics"><i class="fa-solid fa-spray-can-sparkles icons"></i></label>
                                        


                                               

                                                
                                                    <input type="radio" name="icon" id="eatingout" value="fa-solid fa-utensils|výdaj">
                                                    <label  for="eatingout"><i class="fa-solid fa-utensils icons"></i></label>
                                                   

                                                    <br>
                                                        <input type="radio" name="icon" id="health" value="fa-solid fa-pills|výdaj">
                                                        <label  for="health"><i class="fa-solid fa-pills icons"></i></label>
                                                    
                                    

                                                    

                                            
                                                <input type="radio" name="icon" id="education" value="fa-solid fa-graduation-cap|výdaj">
                                                <label  for="education"><i class="fa-solid fa-graduation-cap icons"></i></label>
                                               
    

                                       
                                            <input type="radio" name="icon" id="martiniglass" value="fa-solid fa-martini-glass-citrus|výdaj">
                                            <label  for="martiniglass"><i class="fa-solid fa-martini-glass-citrus icons"></i></label>
                                            


                                         
                                                <input type="radio" name="icon" id="commute" value="fa-solid fa-bus-simple|výdaj">
                                                <label  for="commute"><i class="fa-solid fa-bus-simple icons"></i></label>
                                                

                                                
                                                    <input type="radio" name="icon" id="travel" value="fa-solid fa-plane|výdaj">
                                                    <label  for="travel"><i class="fa-solid fa-plane icons"></i></label>
                                                   
<br>
                                                    
                                                        <input type="radio" name="icon" id="cosmetics" value="fa-solid fa-lightbulb|výdaj">
                                                        <label  for="energy"><i class="fa-solid fa-lightbulb icons"></i></label>
                                                       

                                        


                                                       
                                                            <input type="radio" name="icon" id="water" value="fa-solid fa-droplet|výdaj">
                                                            <label  for="water"><i class="fa-solid fa-droplet icons"></i></label>
                                                         

                                                            

                                                            
                                                                <input type="radio" name="icon" id="gas" value="fa-solid fa-gas-pump|výdaj">
                                                                <label  for="gas"><i class="fa-solid fa-gas-pump icons icons"></i></label>
                                                                


                                                              
                                                                    <input type="radio" name="icon" id="electronics" value="fa-solid fa-display|výdaj">
                                                                    <label  for="electronics"><i class="fa-solid fa-display icons"></i></label>
                                                                    
    

                                                                   
                                                                        <input type="radio" name="icon" id="household" value="fa-solid fa-people-roof|výdaj">
                                                                        <label  for="household"><i class="fa-solid fa-people-roof icons"></i></label>
                                                                        <br>

                                                                        
                                                                            <input type="radio" name="icon" id="heating" value="fa-solid fa-temperature-full|výdaj">
                                                                            <label  for="heating"><i class="fa-solid fa-temperature-full icons"></i></label>
                                                                         

                                                                       

                                                                    
                                                           
                                                                

                                                    <input type="radio" name="icon" id="gift" value="fa-solid fa-gift|výdaj">
                                                    <label  for="gift"><i class="fa-solid fa-gift icons"></i></label>
                                                  

                                                
                                                        <input type="radio" name="icon" id="questionmark" value="fa-solid fa-circle-question|výdaj" checked>
                                                        <label  for="questionmark"><i class="fa-solid fa-circle-question icons" ></i></label>
                                                       




                                        <!-- income icons -->

                                        
                                            <input type="radio" name="icon" id="salary" value="fa-solid fa-hand-holding-dollar|príjem">
                                            <label  for="salary"><i class="fa-solid fa-hand-holding-dollar icons blue"></i></label>
                                            

                                    
                                                <input type="radio" name="icon" id="briefcase" value="fa-solid fa-briefcase|príjem">
                                                <label  for="briefcase"><i class="fa-solid fa-briefcase icons blue"></i></label>
                                            
                                                <br>

                                          
                                                    <input type="radio" name="icon" id="investment" value="fa-solid fa-money-bill-trend-up|príjem">
                                                    <label  for="investment"><i class="fa-solid fa-money-bill-trend-up icons blue"></i></label>
                                                  


                                                
                                               
                                                    <input type="radio" name="icon" id="gift" value="fa-solid fa-gift|príjem">
                                                    <label  for="gift"><i class="fa-solid fa-gift icons blue"></i></label>
                                             





                                        
                                            <input type="radio" name="icon" id="questionmark" value="fa-solid fa-circle-question|príjem">
                                            <label  for="questionmark"><i class="fa-solid fa-circle-question icons blue"></i></label>
                                       


                                         



                    </div>

                 <br>
                   
                </fieldset> 
                <div class="form-group pb-3">
                        <button class='wishlist-button' type="submit">Pridať</button>
                    </div>
            </form>
        </div>
    </div>
</div>
<br><br>

    
{% endblock %}

Projekt/website/templates/addTransaction.html
{% extends 'base.html' %} {% block content %}
<div class="col-xs-10 col-sm-6 col-md-6 ml-auto mr-auto">
  <div class="card card-style mb-2">
    <div class="card-body transaction-form">
      <form action="{{url_for('views.addTransaction')}}" method="POST">
        <fieldset class="form-group">
          <legend class="mb-4">Nová Transakcia</legend>

          <div class="form-group">
            <label class="inputLabel" for="amount">Suma </label>

            <input
              type="number"
              step="0.01"
              required
              id="amount"
              name="amount"
              autocomplete="off"
            />
          </div>
          <br />

          <div class="categories-box">
            {% for category in categories %} {% if category.name == 'výdaj' %}

            <label class="transaction-card" for="{{category.type}}">
              <input
                type="radio"
                required
                name="icon"
                id="{{category.type}}"
                value="{{category.type}}|{{category.name}}"
              />

              <i style="margin-left: 10px" class="{{category.icon}}"></i
              ><span> {{category.type}}</span></label
            >

            {% endif %} {% endfor %} {% for category in categories %} {% if
            category.name == 'príjem' %}

            <label class="transaction-card blue" for="{{category.type}}">
              <input
                type="radio"
                name="icon"
                id="{{category.type}}"
                value="{{category.type}}|{{category.name}}"
              />

              <i style="margin-left: 10px" class="{{category.icon}}"></i
              ><span> {{category.type}}</span></label
            >

            {% endif %} {% endfor %}
          </div>

          <br />

          <br />
        </fieldset>
        <div class="form-group pb-3">
          <button class="wishlist-button" type="submit">Pridať</button>
        </div>
      </form>
    </div>
  </div>
</div>
<br /><br />

{% endblock %}

Projekt/website/templates/base.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />

    <script
      src="https://kit.fontawesome.com/9481b93cfb.js"
      crossorigin="anonymous"
    ></script>
  
    <script src="https://cdn.jsdelivr.net/npm/chart.js@2.8.0"></script>

    <!-- google fonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <link
      href="https://fonts.googleapis.com/css2?family=Nunito+Sans:wght@300&display=swap"
      rel="stylesheet"
    />

    <link rel="stylesheet" href="../static/main.css" />

    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
      integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh"
      crossorigin="anonymous"
    />
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"
      crossorigin="anonymous"
    />

    <title>{% block title %}onBudget{% endblock %}</title>
    <link rel="shortcut icon" href="../static/img/logo-teal.png" />
  </head>
  <body>
    <nav class="navbar navbar-expand-sm navbar-dark bg-dark">
      <a href="/" class="navbar-brand">
        <img src="../static/img/logo-teal.png" width="50" alt="" />
        <span class="onBudget">onBudget</span>
      </a>

      <button
        class="navbar-toggler"
        type="button"
        data-toggle="collapse"
        data-target="#navbar"
      
      >


        <span class="navbar-toggler-icon"></span>
      </button>
     


      <div class="collapse navbar-collapse" id="navbar">
        <div class="navbar-nav">
          <a class="nav-item nav-link" id="home" href="/">Domov</a>
          <a class="nav-item nav-link" id="transactions" href="/transactions"
            >Transakcie</a
          >

          <a class="nav-item nav-link" id="categories" href="/categories"
            >Kategórie</a
          >

          
          <a class="nav-item nav-link" id="charts" href="/charts">Prehľad</a>
          <a class="nav-item nav-link" id="wishlist" href="/wishlist"
            >Wishlist</a
          >

          <a class="nav-item nav-link" id="logout" href="/logout"
            >Odhlásiť sa</a
          >

          <!-- toggle button -->


          <div id="toggle-button" class="">
            <i class="indicator" onclick="playAudio('https://www.fesliyanstudios.com/play-mp3/387')"></i>

            

          </div>
          <!-- https://www.fesliyanstudios.com/play-mp3/387 -->
        </div>
      </div>
    </nav>

    {% with messages = get_flashed_messages(with_categories=true) %} {% if
    messages %} {% for category, message in messages %} {% if category ==
    'error' %}
    <div class="alert alert-danger alter-dismissable fade show" role="alert">
      {{ message }}
      <button type="button" class="close" data-dismiss="alert">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
    {% else %}
    <div class="alert alert-success alter-dismissable fade show" role="alert">
      {{ message }}
      <button type="button" class="close" data-dismiss="alert">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
    {% endif %} {% endfor %} {% endif %} {% endwith %}

    <div class="container">
      <br /><br />
      {% block content %} {% endblock %}
    </div>
    <script
      src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
      integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
      integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
      integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
      crossorigin="anonymous"
    ></script>

    <script
      type="text/javascript"
      src="{{ url_for('static', filename='index.js') }}"
    ></script>
 
  </body>
</html>

Projekt/website/templates/categories.html
{% extends "base.html" %} {% block title %}Kategórie{% endblock %} 


{% block
content%}

<br />


    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <style>
      .table-responsive {
        border-radius: 20px;
      }
      .table-wrapper {
        width: 50%;
        background: rgb(255, 255, 255);
        border-radius: 20px;
        padding: 20px;
        box-shadow: 0 1px 1px rgba(0, 0, 0, 0.05);
        margin: 0 auto;
      }
      .table-title {
        padding-bottom: 10px;
        margin: 0 0 10px;
      }
      .table-title h2 {
        margin: 8px 0 0;
        font-size: 22px;
      }

      .add-button {
        position: relative;
        float: right;
        font-size: 30px;
        color: #50cab5e3;
      }

      .add-button:hover,
      .table td a.edit:hover,
      .table td a.delete:hover {
        color: rgb(100, 224, 211);
      }
   
      table.table tr th,
      table.table tr td {
        border-color: #a6d3cc71;
      }
      table.table-striped tbody tr:nth-of-type(odd) {
        background-color: #fcfcfc;
      }
      table.table-striped.table-hover tbody tr:hover {
        background-color: #65b9ab2a;
      }
      table.table th i {
        font-size: 13px;
        margin: 0 5px;
        cursor: pointer;
      }
      table.table td:last-child {
        width: 50px;
      }
      table.table td a {
        color: #a0a5b1;
        display: inline-block;
        margin: 0 5px;
      }

      table.table td a.edit {
        color: #50cab5e3;
      }
      table.table td a.delete {
        color: #50cab5e3;
      }
      table.table td i {
        font-size: 19px;
      }

      .table {
        line-height: 17px;
        width: 100%;
      }

      .scrollable-table {
        overflow: hidden;
        overflow-y: scroll;
        height: 177.2px;
        border: 1px solid rgba(128, 128, 128, 0.198);
      }
      .transaction-type {
        float: right;
        text-align: center;
        width: 80px;
        padding: 5px 10px;
        border-radius: 15px;
      }

      .transaction-type.income {
        background-color: #77dd773f;
      }

      .transaction-type.expense {
        background-color: #ff6d6a46;
      }
    </style>
  </head>
  <body>
    <div class="table-responsive">
      <div class="table-wrapper">
        <div class="table-title">
          <div class="row">
            <div class="col-sm"><h2>Kategórie</h2></div>
            <div class="col-sm">
              <div>
                <a href="/addCategory"
                  ><i class="fa-sharp fa-solid fa-circle-plus add-button"></i
                ></a>
              </div>
              <!-- <div class="search-box">
                               
                                <i class="material-icons">&#xE8B6;</i>
                                <input type="text" class="form-control" placeholder="Search&hellip;">

                            </div> -->
            </div>
          </div>
        </div>
        <div class="scrollable-table">
          <table class="table table-striped table-hover table-bordered">
            <thead>
              <tr>
                <th>Výdaj</th>
              </tr>
            </thead>
            <tbody>
              {% for entry in entries %}

              <tr>
              

                {% if entry.name == 'výdaj' %}

                <td>
                  <i style="color: #2ebf91" class="{{ entry.icon }}"></i
                  ><span> {{ entry.type }}</span>
                </td>

                <td>
                  <a
                    href="{{ url_for('views.deleteCategory', id = entry.id) }}"
                    class="delete"
                    title="Delete"
                    ><i class="fa-solid fa-trash-can-arrow-up"></i
                  ></a>
                </td>

                {% endif %}
              </tr>
              {% endfor %}
            </tbody>
          </table>
        </div>
        <br />

        <div class="scrollable-table">
          <table class="table table-striped table-hover table-bordered">
            <thead>
              <tr>
                <th>Príjem</th>
                <th></th>
              </tr>
            </thead>
            <tbody>
              {% for entry in entries %}

              <tr>
                {% if entry.name == 'príjem' %}

                <td>
                  <i
                    style="color: rgb(62, 176, 193)"
                    class="{{ entry.icon }}"
                  ></i
                  ><span> {{ entry.type }}</span>
                </td>

                <td>
                  <a
                    href="{{ url_for('views.deleteCategory', id = entry.id) }}"
                    class="delete"
                    title="Delete"
                    ><i class="fa-solid fa-trash-can-arrow-up"></i
                  ></a>
                </td>

                {% endif %}
              </tr>
              {% endfor %}
            </tbody>
          </table>
        </div>
      </div>
    </div>
    <br /><br />
  </body>
</html>

{% endblock %}